#!/usr/bin/env php
<?php

declare(strict_types=1);

defined('YII_DEBUG') or define('YII_DEBUG', filter_var(getenv('APP_DEBUG') ?: false, FILTER_VALIDATE_BOOL));

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$exitCode = (new yii\console\Application(require __DIR__ . '/config/console.php'))->run();
exit($exitCode);
