<script setup>
import { onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { adminApi } from '../api'
import { createLatestRequestGuard } from '../latestRequestGuard'
import AppIcon from './AppIcon.vue'
import AppModal from './AppModal.vue'
const emit = defineEmits(['open-request'])
const items = ref([]); const cursor = ref(null); const hasMore = ref(false); const loading = ref(false); const error = ref(''); const selected = ref(null)
const filters = reactive({ status: '', requestId: '', eventType: '', recipient: '', problematic: '', dateFrom: '', dateTo: '', limit: 50 })
const guard = createLatestRequestGuard()
async function load(more = false) { const token = guard.begin(true); loading.value = true; error.value = ''; try { const result = await adminApi.notifications({ ...filters, cursor: more ? cursor.value : null }); if (!guard.isCurrent(token, true)) return; items.value = more ? [...items.value, ...(result.items || [])] : (result.items || []); cursor.value = result.nextCursor; hasMore.value = Boolean(result.hasMore) } catch { if (guard.isCurrent(token, true)) error.value = 'Не удалось загрузить журнал уведомлений.' } finally { if (guard.isCurrent(token, true)) loading.value = false } }
function submit() { cursor.value = null; load(false) }
function localTime(value) { return value ? new Intl.DateTimeFormat('ru-RU', { dateStyle: 'short', timeStyle: 'medium' }).format(new Date(value)) : '—' }
function tone(item) { return item.health === 'failed' || item.health === 'stale' ? 'red' : item.health === 'retrying' ? 'orange' : item.status === 'sent' ? 'green' : 'blue' }
function healthLabel(value) { return { failed: 'Ошибка', stale: 'Просрочено', retrying: 'Повторная попытка', normal: 'В норме' }[value] || 'Неизвестно' }
onMounted(() => load()); onBeforeUnmount(() => guard.invalidate())
</script>
<template><section class="admin-log" aria-labelledby="admin-tab-notifications">
  <form class="admin-filters" @submit.prevent="submit"><label>Статус<select v-model="filters.status"><option value="">Все</option><option value="pending">Ожидает</option><option value="sending">Отправляется</option><option value="sent">Отправлено</option><option value="failed">Ошибка</option></select></label><label>Заявка<input v-model="filters.requestId" type="number" min="1"></label><label>Событие<input v-model.trim="filters.eventType"></label><label>Получатель<input v-model.trim="filters.recipient"></label><label>Проблемные<select v-model="filters.problematic"><option value="">Все</option><option value="1">Только проблемные</option></select></label><label>С<input v-model="filters.dateFrom" type="date"></label><label>По<input v-model="filters.dateTo" type="date"></label><button class="secondary">Применить</button></form>
  <div v-if="error" class="admin-state admin-state--error"><span>{{ error }}</span><button type="button" class="secondary" @click="load(false)">Повторить</button></div><div v-else-if="loading && !items.length" class="admin-state">Загрузка…</div>
  <div v-else-if="items.length" class="table-wrap admin-table-wrap admin-log-table"><table class="admin-table"><thead><tr><th>Создано</th><th>Заявка</th><th>Получатель</th><th>Событие</th><th>Статус</th><th>Попытки</th><th>Отправлено</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" tabindex="0" @click="selected = item" @keydown.enter.self="selected = item" @keydown.space.self.prevent="selected = item"><td>{{ localTime(item.createdAt) }}</td><td><button type="button" class="admin-link" @click.stop="emit('open-request', item.requestId)">{{ item.requestLabel }}</button></td><td>{{ item.recipient.name }}<small>{{ item.recipient.email }}</small></td><td>{{ item.eventTitle }}</td><td><span class="badge" :class="tone(item)">{{ item.statusLabel }}</span></td><td>{{ item.attempts }}</td><td>{{ localTime(item.sentAt) }}</td></tr></tbody></table></div><div v-else class="admin-empty"><div class="admin-empty-icon" aria-hidden="true"><AppIcon name="search" :size="20" /></div><h3>Уведомления не найдены</h3><p>Измените параметры фильтрации.</p></div>
  <div v-if="hasMore" class="admin-more"><button type="button" class="secondary" :disabled="loading" @click="load(true)">{{ loading ? 'Загрузка…' : 'Показать ещё' }}</button></div>
  <AppModal :open="Boolean(selected)" title="Детали уведомления" title-id="admin-notification-detail-title" size="medium" @close="selected = null"><dl v-if="selected" class="admin-details"><dt>Событие</dt><dd>{{ selected.eventTitle }}</dd><dt>Тип события</dt><dd>{{ selected.eventType }}</dd><dt>Заявка</dt><dd>{{ selected.requestLabel }}</dd><dt>Получатель</dt><dd>{{ selected.recipient.name }} — {{ selected.recipient.email }}</dd><dt>Тема</dt><dd>{{ selected.subject }}</dd><dt>Состояние</dt><dd>{{ selected.statusLabel }} · {{ healthLabel(selected.health) }}</dd><dt>Повторная попытка или окончание блокировки</dt><dd>{{ selected.nextAttemptAt }}</dd><template v-if="selected.lastError"><dt>Ошибка</dt><dd class="plain-error">{{ selected.lastError }}</dd></template></dl></AppModal>
</section></template>
