<script setup>
const actStages = [
  ['1', 'Регистрация', 'Сотрудник создаёт заявку'],
  ['2', 'Маршрут и исполнитель', 'Руководитель выбирает «Акт» и назначает исполнителя'],
  ['3', 'Испытания и отчёт', 'Исполнитель проводит испытания и загружает PDF'],
  ['4', 'Завершение', 'Руководитель проверяет отчёт и завершает заявку'],
]
const protocolStages = [
  ['1', 'Регистрация', 'Сотрудник создаёт заявку'],
  ['2', 'Маршрут и исполнитель', 'Руководитель выбирает «Протокол» и назначает исполнителя'],
  ['3', 'Испытания и отчёт', 'Исполнитель проводит испытания и загружает PDF'],
  ['4', 'Экспертиза', 'Эксперт публикует заключение'],
  ['5', 'Контроль СБ', 'СБ выбирает «Согласовано» или «Не согласовано»'],
  ['6', 'Завершение', 'Заявка завершается автоматически после любого решения СБ'],
]
const roles = [['Сотрудник', 'Создаёт заявки и получает результат'], ['Руководитель ИЦ / лаборатории', 'Выбирает маршрут, назначает исполнителя и завершает Акт'], ['Исполнитель ИЦ', 'Проводит испытания и загружает отчёт'], ['Эксперт', 'Формирует экспертное заключение'], ['Сотрудник СБ', 'Согласует или не согласует; оба решения завершают Протокол'], ['Администратор', 'Управляет доступом и исправляет решение СБ по обращению в ИТ']]

function returnToPortal() {
  window.dispatchEvent(new CustomEvent('ic:close-review-guide'))
}
</script>

<template>
  <article class="guide-page">
    <header class="guide-intro"><p>Обзор портала</p><h2>Реестр заявок на проведение испытаний</h2><span>Объекты испытаний, документы, маршруты «Акт» и «Протокол» и действия участников. Актуально на 05.10.2026 · версия 0.1.0.</span><p class="guide-image-note">Нажмите на иллюстрацию, чтобы открыть её в полном разрешении.</p></header>

    <section class="guide-section">
      <div class="section-copy"><span>01</span><div><h3>Реестр заявок</h3><p>Вкладки разделяют активные, все и личные заявки. Поиск, фильтр статусов и выбор одного или нескольких направлений испытаний работают совместно. Поиск находит любую позицию многопозиционной заявки. Шапка таблицы закреплена при прокрутке; в низком окне весь реестр прокручивается со страницей. В строке видны объект испытаний, участники, статус, решение СБ, последний комментарий и наличие отчёта.</p></div></div>
      <figure class="screen"><a class="screenshot-link" href="/review-guide-assets/registry-list-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/registry-list-hires.png" alt="Реестр заявок"></a><figcaption>Нажатие на строку открывает карточку заявки. Цветная полоса слева обозначает направление испытаний, а статус показан нейтральным текстом. Фильтр в узком первом столбце выбирает направления; сортировка по номеру сохраняется. Подсказка объекта перечисляет все позиции отдельными строками.</figcaption></figure>
    </section>

    <section class="guide-section">
      <div class="section-copy"><span>02</span><div><h3>Рабочие очереди</h3><p>Блок «Требуют вашего внимания» собирает персональные задачи пользователя по доступным действиям, а не показывает статистику по статусам.</p></div></div>
      <figure class="screen queue-screen"><a class="screenshot-link" href="/review-guide-assets/queue-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/queue-hires.png" alt="Персональные рабочие очереди"></a><figcaption>Категории зависят от ролей, назначений и текущего этапа заявок. Выбор категории фильтрует основной реестр.</figcaption></figure>
      <div class="callout"><b>Зачем это нужно</b><span>Пользователю не требуется самостоятельно искать заявки, в которых наступил его этап: система сразу показывает вид действия и количество задач.</span></div>
    </section>

    <section class="guide-section">
      <div class="section-copy"><span>03</span><div><h3>Уведомления в портале</h3><p>Кнопка уведомлений расположена в правой части панели реестра. Синяя точка означает, что после последнего просмотра появились новые события.</p></div></div>
      <div class="notification-stack"><figure class="screen"><a class="screenshot-link" href="/review-guide-assets/notification-strip-marked-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/notification-strip-marked-hires.png" alt="Положение кнопки уведомлений в реестре"></a><figcaption>Кнопка находится справа от поиска и фильтра. Синяя точка отмечает новые события.</figcaption></figure><figure class="screen"><a class="screenshot-link" href="/review-guide-assets/notifications-context-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/notifications-context-hires.png" alt="Окно уведомлений поверх реестра"></a><figcaption>Окно открывается поверх реестра. Из списка можно сразу перейти в заявку, где произошло событие.</figcaption></figure></div>
    </section>

    <section class="guide-section">
      <div class="section-copy"><span>04</span><div><h3>Карточка заявки</h3><p>Рядом с номером и датой показаны ФИО, должность и подразделение инициатора. Кнопки копирования отдельно копируют заявку с инициатором, название позиции или все названия с поставщиком. При неоднозначном склонении портал просит проверить текст. Набор действий зависит от роли и статуса.</p></div></div>
      <div class="request-features"><article><b>Умная лента</b><p>Комментарии сотрудников и события процесса показаны вместе и расположены по времени. Пользователь видит не только обсуждение, но и назначения, смену статуса, загрузку отчёта, публикацию заключения и решение СБ, а также историю его исправлений.</p></article><article><b>Документы разделены по назначению</b><p>В правой колонке отдельно собраны сопроводительные документы, отчёты об испытаниях и экспертные заключения. Для каждого файла видны версия, размер, автор и время загрузки по Москве. Для старых вложений без этих данных показаны «Автор неизвестен» и «Дата загрузки неизвестна».</p></article><article><b>Участники и контроль СБ</b><p>Рядом с документами указаны инициатор, исполнитель, эксперт и последнее решение службы безопасности.</p></article></div>
      <figure class="screen request-overview sharp-screen"><a class="screenshot-link" href="/review-guide-assets/request-overview-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/request-overview-hires.png" alt="Карточка заявки с лентой, участниками и документами"></a><figcaption>Статус и направление находятся вверху справа, маршрут — над процессом. Список нескольких объектов раскрыт для руководителей и исполнителя ИЦ, свёрнут для остальных ролей, включая эксперта. Одну позицию видно сразу.</figcaption></figure>
    </section>

    <section class="guide-section">
      <div class="section-copy"><span>05</span><div><h3>Встроенная справка</h3><p>Для знакомства пользователей с новым порталом в интерфейс добавлена внутренняя справка. Нажмите значок <b>?</b> рядом с рабочей очередью или процессным действием — инструкция откроется справа, не закрывая контекст текущей страницы.</p></div></div>
      <div class="help-locations"><figure class="screen"><a class="screenshot-link" href="/review-guide-assets/help-location-queue-marked-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/help-location-queue-marked-hires.png" alt="Кнопка справки рядом с заголовком рабочих очередей"></a><figcaption><b>1. Рабочие очереди.</b> Кнопка <b>?</b> находится рядом с заголовком «Требуют вашего внимания».</figcaption></figure><figure class="screen"><a class="screenshot-link" href="/review-guide-assets/help-location-card-marked-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/help-location-card-marked-hires.png" alt="Кнопка справки рядом с процессным действием"></a><figcaption><b>2. Карточка заявки.</b> Кнопка <b>?</b> находится справа от доступного действия.</figcaption></figure></div>
      <figure class="screen help-example"><a class="screenshot-link" href="/review-guide-assets/help-open-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/help-open-hires.png" alt="Пример открытой справки поверх страницы реестра"></a><figcaption><b>3. Пример открытой справки.</b> Инструкция появляется справа и сохраняет видимым исходный экран.</figcaption></figure>
    </section>

    <section id="request-routes" class="guide-section compact-section">
      <div class="section-copy"><span>06</span><div><h3>Маршруты «Акт» и «Протокол»</h3><p>Руководитель ИЦ или лаборатории выбирает маршрут до начала работ. Менять его можно до первой загрузки отчёта; удаление отчёта не открывает смену маршрута. Процесс общий для всех объектов заявки.</p></div></div>
      <div class="route-comparison">
        <div class="route-lane" aria-labelledby="act-route-title">
          <h4 id="act-route-title">Акт<span>Без экспертизы и СБ</span></h4>
          <ol class="route-steps"><li v-for="stage in actStages" :key="stage[0]" class="route-step"><span class="route-step-number" aria-hidden="true">{{ stage[0] }}</span><div><b>{{ stage[1] }}</b><span>{{ stage[2] }}</span></div></li></ol>
        </div>
        <div class="route-lane" aria-labelledby="protocol-route-title">
          <h4 id="protocol-route-title">Протокол<span>С экспертизой и СБ</span></h4>
          <ol class="route-steps"><li v-for="stage in protocolStages" :key="stage[0]" class="route-step"><span class="route-step-number" aria-hidden="true">{{ stage[0] }}</span><div><b>{{ stage[1] }}</b><span>{{ stage[2] }}</span></div></li></ol>
        </div>
      </div>
      <p class="route-scale-note">Один блок — один шаг процесса. Одинаковые шаги расположены на одном уровне; длительность работ схема не отражает.</p>
      <div class="route-explanations">
        <p><b>Завершение по акту.</b> После загрузки отчёта заявка остаётся в работе. Руководитель ИЦ или лаборатории проверяет документ и нажимает «Завершить заявку». Экспертное заключение и решение СБ не требуются.</p>
        <p><b>Завершение по протоколу.</b> После отчёта нужны экспертное заключение и решение СБ — «Согласовано» или «Не согласовано». Любое решение СБ автоматически завершает заявку; дополнительного завершения руководителем или экспертом нет. Возврата из СБ на доработку нет.</p>
      </div>
    </section>

    <section class="guide-section">
      <div class="section-copy"><span>07</span><div><h3>Почтовые уведомления и итоговые документы</h3><p>Письмо содержит номер заявки, объекты испытаний, ожидаемое действие и ссылки на заявку или документ. Для нескольких позиций документы и письма перечисляют объекты с количеством. Генератор DOCX создаёт редактируемый черновик акта: он не выбирает маршрут и не заменяет загрузку утверждённого PDF.</p></div></div>
      <div class="document-grid"><figure class="screen"><a class="screenshot-link" href="/review-guide-assets/email-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/email-hires.png" alt="Почтовое уведомление о передаче заявки на экспертизу"></a><figcaption><b>Почтовое уведомление.</b> В маршруте «Протокол» эксперт получает сообщение после загрузки отчёта.</figcaption></figure><figure class="screen"><a class="screenshot-link" href="/review-guide-assets/expert-opinion-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/expert-opinion-hires.png" alt="Сформированное экспертное заключение"></a><figcaption><b>Экспертное заключение.</b> Портал формирует PDF из текста эксперта и данных заявки.</figcaption></figure></div>
    </section>

    <section id="request-creation" class="guide-section">
      <div class="section-copy"><span>08</span><div><h3>Создание заявки и сохранение черновика</h3><p>В заявке от 1 до 10 объектов. Для каждой позиции укажите наименование и своё текстовое количество образцов до 15 символов, например «4 шт по 3 метра». Производитель, поставщик и объём испытаний общие для всех позиций.</p>
        <ul class="creation-rules">
          <li><b>Добавить позицию:</b> нажмите «Добавить объект» — появится новая строка с наименованием и количеством образцов.</li>
          <li><b>Удалить позицию:</b> нажмите значок корзины справа от её строки. В заявке должен остаться хотя бы один объект; единственную позицию удалить нельзя.</li>
          <li><b>Лимит:</b> счётчик показывает количество объектов из 10. Когда добавлены 10 объектов, кнопка «Добавить объект» недоступна. После удаления позиции можно добавить другую.</li>
        </ul>
        <p>Можно выбрать или перетащить несколько сопроводительных файлов, добавить ещё и удалить ошибочно выбранный до отправки. Файлы загрузятся после создания заявки.</p></div></div>
      <figure class="screen draft-screen sharp-screen"><a class="screenshot-link" href="/review-guide-assets/request-create-objects-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/request-create-objects-hires.png" alt="Создание заявки с тремя объектами: счётчик 3 из 10, кнопка Добавить объект и корзина у каждой позиции"></a><figcaption>Три объекта в одной заявке: отдельные названия и количества, общие производитель, поставщик и объём испытаний. Кнопка под списком добавляет строку, корзина справа удаляет выбранную позицию.</figcaption></figure>
      <p class="process-note">Портал сохраняет введённые данные в локальном черновике на 30 дней, если хранилище браузера доступно. После обновления страницы или повторного входа под тем же профилем в том же браузере форма восстановится. Файлы потребуется выбрать повторно. После успешного создания заявки черновик удаляется.</p>
    </section>

    <section class="guide-section compact-section">
      <div class="section-copy"><span>09</span><div><h3>Роли и проверка полного маршрута</h3><p>Пользователь видит только доступные ему процессные действия. В демонстрационной версии в шапке доступен переключатель пользователей: он позволяет последовательно проверить весь маршрут заявки и состояние системы от лица каждого участника.</p></div></div>
      <figure class="screen role-switcher-shot"><a class="screenshot-link" href="/review-guide-assets/role-switcher-marked-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/role-switcher-marked-hires.png" alt="Переключатель пользователей в демонстрационной версии"></a><figcaption>После выбора профиля страница перезагружается с его ролями, рабочими очередями и доступными действиями. В промышленной версии переключатель отсутствует.</figcaption></figure>
      <div class="roles"><article v-for="role in roles" :key="role[0]"><b>{{ role[0] }}</b><span>{{ role[1] }}</span></article></div>
    </section>

    <section class="guide-section">
      <div class="section-copy"><span>10</span><div><h3>Администрирование</h3><p>Раздел предназначен для системных администраторов. Он позволяет управлять пользователями, ролями и журналами. Активный администратор может исправить последнее решение СБ в карточке заявки, в том числе завершённой. Обязательны причина и номер или ссылка на обращение в ИТ. Исходное решение и все исправления сохраняются в ленте с автором и временем. Статус, назначения и документы не меняются; повторное письмо о завершении не отправляется. Импортный архив остаётся только для чтения.</p></div></div>
      <figure class="screen"><a class="screenshot-link" href="/review-guide-assets/admin-crop-hires.png" target="_blank" rel="noopener" title="Открыть изображение в полном разрешении"><img src="/review-guide-assets/admin-crop-hires.png" alt="Основные элементы раздела администрирования"></a><figcaption><b>Пользователи и роли</b> — состав доступа. <b>Журнал действий</b> — значимые операции. <b>Уведомления</b> — состояние отправки писем.</figcaption></figure>
    </section>

    <footer class="guide-footer"><div><b>Конец обзора</b><span>Вернитесь в рабочий реестр, чтобы продолжить работу с заявками.</span></div><button type="button" @click="returnToPortal">Вернуться в портал</button></footer>
  </article>
</template>

<style scoped>
.guide-page{width:min(calc(100% - 84px),1360px);margin:0 auto 34px;color:#142033}.guide-intro{border:1px solid #dde3ec;border-radius:14px;background:#fff;padding:26px 30px}.guide-intro p{margin:0 0 7px;color:#253d98;font-size:10px;font-weight:600;letter-spacing:.08em;text-transform:uppercase}.guide-intro h2{margin:0 0 7px;font-size:27px;line-height:1.2}.guide-intro span{color:#657286;font-size:12px}.guide-section{border-bottom:1px solid #dde3ec;padding:36px 0}.section-copy{display:grid;grid-template-columns:34px minmax(0,780px);gap:14px;margin:0 14px 20px}.section-copy>span{width:32px;height:32px;display:grid;place-items:center;border-radius:50%;background:#e8ebfb;color:#253d98;font-size:10px;font-weight:600}.section-copy h3{margin:3px 0 7px;font-size:20px}.section-copy p{margin:0;color:#536075;font-size:12px;line-height:1.55}.screen{position:relative;margin:0;border:1px solid #d9dfe8;border-radius:12px;background:#fff;overflow:hidden;box-shadow:0 3px 14px rgba(20,32,51,.05)}.screen img{display:block;width:100%;height:auto}.screen figcaption{border-top:1px solid #e7ebf0;padding:11px 14px;color:#657286;font-size:10px;line-height:1.5}.screen figcaption b{color:#263348}.callout{display:flex;gap:16px;margin-top:11px;border-radius:10px;background:#eef1f6;padding:11px 14px;font-size:10px}.callout b{white-space:nowrap}.callout span{color:#536075}.image-marker{position:absolute;z-index:2;right:18px;bottom:45px;border-radius:13px;background:#253d98;padding:6px 10px;color:#fff;font-size:9px;font-weight:600;box-shadow:0 3px 10px rgba(37,61,152,.25)}.detail-grid,.help-grid,.document-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;align-items:start}.help-grid .screen img{height:490px;object-fit:cover;object-position:top}.document-grid img{height:500px;object-fit:cover;object-position:top}.compact-section{padding-bottom:30px}.process-note{margin:11px 0 0;border-radius:10px;background:#eef1f6;padding:11px 14px;color:#536075;font-size:10px}.roles{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.roles article{display:grid;gap:5px;border:1px solid #dde3ec;border-radius:10px;background:#fff;padding:13px}.roles b{font-size:11px}.roles span{color:#657286;font-size:9px;line-height:1.4}.guide-footer{display:flex;justify-content:space-between;gap:20px;margin-top:22px;border:1px solid #dde3ec;border-radius:12px;background:#fff;padding:17px 20px;font-size:11px}.guide-footer span{color:#657286}@media(max-width:900px){.detail-grid,.help-grid,.document-grid,.roles{grid-template-columns:1fr}.help-grid .screen img,.document-grid img{height:auto}}@media(max-width:700px){.guide-page{width:calc(100% - 28px)}.guide-intro{padding:20px}.guide-intro h2{font-size:22px}.guide-section{padding:28px 0}.section-copy{margin:0 3px 17px}.callout,.guide-footer{display:grid}}
.notification-grid{display:grid;grid-template-columns:180px 24px minmax(0,1fr);gap:12px;align-items:center}.notification-button-shot{padding:32px;background:#f3f5f9}.notification-button-shot img{width:56px;margin:auto}.flow-arrow{text-align:center;color:#253d98;font-size:18px}.notification-grid .image-marker,.help-flow .image-marker{top:8px;right:8px;bottom:auto}.request-images{display:grid;gap:12px}.request-images .screen img{width:100%}.help-cases{display:grid;gap:20px}.help-cases article{border:1px solid #dde3ec;border-radius:12px;background:#f8f9fb;padding:14px}.help-cases h4{margin:0 0 12px;font-size:12px}.help-flow{display:grid;grid-template-columns:minmax(0,1.15fr) 24px minmax(260px,.85fr);gap:10px;align-items:center}.trigger-shot img{max-height:300px;object-fit:cover;object-position:top}.drawer-shot img{height:390px;object-fit:cover;object-position:top}.help-flow .action-marker{top:auto;bottom:8px}.document-grid{grid-template-columns:1fr;gap:18px}.document-grid .screen{width:min(100%,1120px)}.document-grid img{height:680px;object-fit:cover;object-position:top}.document-grid .screen:nth-child(2){width:min(100%,900px)}
.role-switcher-shot{margin-bottom:12px}.role-switcher-shot .image-marker{top:8px;right:235px;bottom:auto}
@media(max-width:900px){.help-flow{grid-template-columns:1fr}.help-flow .flow-arrow{transform:rotate(90deg)}.drawer-shot img,.document-grid img{height:auto}.notification-grid{grid-template-columns:150px 24px minmax(0,1fr)}}
@media(max-width:700px){.notification-grid{grid-template-columns:1fr}.notification-grid .flow-arrow{transform:rotate(90deg)}}
.notification-stack,.help-contexts{display:grid;gap:14px}.notification-stack .screen:nth-child(2){width:min(100%,1120px)}.notification-marker{top:50%;right:18px;bottom:auto;transform:translateY(-50%)}.request-overview,.help-contexts .screen{overflow:visible}.feature-marker{position:absolute;z-index:3;border-radius:13px;background:#253d98;padding:6px 10px;color:#fff;font-size:9px;font-weight:600;box-shadow:0 3px 10px rgba(37,61,152,.25)}.feed-marker{top:51%;left:23%}.people-marker{top:32%;right:10%}.docs-marker{top:58%;right:9%}.help-contexts .screen{overflow:hidden}.help-contexts .screen img{display:block;width:100%;height:auto}.help-marker{top:18px;left:18px}.role-switcher-shot{margin-bottom:12px}.switcher-note{display:flex;align-items:center;gap:14px;border-top:1px solid #e7ebf0;background:#eef1f6;padding:11px 18px;font-size:10px}.switcher-note b{color:#253d98}.switcher-note span{color:#536075}
@media(max-width:700px){.feature-marker{position:static;display:inline-flex;margin:8px 8px 0}.request-overview,.help-contexts .screen{display:flex;flex-direction:column}.request-overview img,.help-contexts .screen img{order:2}.request-overview figcaption,.help-contexts figcaption{order:3}.switcher-note{display:grid}}
:global(.development-tools-guide){background:#253d98!important;color:#fff!important;font-weight:600!important}
.notification-ring,.help-ring{position:absolute;z-index:3;border:3px solid #253d98;border-radius:50%;box-shadow:0 0 0 4px rgba(37,61,152,.14);pointer-events:none}.notification-ring{top:46%;right:.8%;width:4%;aspect-ratio:1}.request-features{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;margin-top:12px}.request-features article{border:1px solid #dde3ec;border-radius:10px;background:#fff;padding:14px}.request-features b{font-size:11px}.request-features p{margin:6px 0 0;color:#536075;font-size:10px;line-height:1.55}.help-locations{display:grid;gap:12px}.help-ring{width:38px;height:38px}.queue-ring{top:10px;left:17.4%}.action-ring{right:3.1%;bottom:36px}.help-example{margin-top:14px}.help-example img{width:100%;height:auto}
@media(max-width:900px){.request-features{grid-template-columns:1fr}.queue-ring{width:30px;height:30px}.action-ring{width:32px;height:32px}}
.draft-screen{width:min(100%,980px)}.guide-footer{align-items:center}.guide-footer div{display:grid;gap:5px}.guide-footer button{flex:none;border:0;border-radius:8px;background:#253d98;padding:10px 16px;color:#fff;font:inherit;font-weight:600;cursor:pointer}@media(max-width:700px){.guide-footer button{justify-self:start}}
.creation-rules{margin:12px 0;padding-left:20px;color:#536075;font-size:12px;line-height:1.55}.creation-rules li + li{margin-top:8px}
.route-comparison{--route-step-height:94px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;max-width:1000px;margin:0 auto}.route-lane{min-width:0}.route-lane h4{margin:0 0 18px;font-size:22px;line-height:1.3}.route-lane h4>span{display:block;margin-top:4px;font-size:12px;font-weight:400;color:#536075}.route-steps{display:grid;grid-auto-rows:var(--route-step-height);gap:18px;list-style:none;margin:0;padding:0}.route-step{position:relative;display:flex;align-items:flex-start;gap:12px;padding:16px;background:#fff;border:1px solid #dde3ec;border-radius:10px;min-width:0}.route-step:not(:last-child)::after{content:'';position:absolute;left:28px;bottom:-14px;width:7px;height:7px;border-right:2px solid #8793a5;border-bottom:2px solid #8793a5;transform:rotate(45deg)}.route-step-number{display:grid;place-items:center;flex:none;width:24px;height:24px;border-radius:50%;background:#253d98;color:#fff;font-size:11px}.route-step div{display:grid;gap:6px;min-width:0}.route-step b{font-size:13px;line-height:1.35}.route-step div>span{color:#536075;font-size:12px;line-height:1.4}.route-scale-note{margin:18px 0;color:#536075;font-size:11px;text-align:center}.route-explanations{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.route-explanations p{margin:0;color:#536075;font-size:12px;line-height:1.55}.route-explanations b{color:#142033}.sharp-screen img{object-fit:contain}.request-overview.sharp-screen{max-width:1360px}.draft-screen.sharp-screen{max-width:820px}
@media(max-width:700px){.route-comparison{--route-step-height:156px;gap:12px}.route-lane h4{font-size:18px;min-height:48px}.route-step{display:block;padding:12px}.route-step-number{margin-bottom:8px}.route-step b{font-size:12px}.route-step div>span{font-size:11px}.route-step:not(:last-child)::after{left:20px}.route-explanations{grid-template-columns:1fr;gap:12px}}
@media(max-width:360px){.route-comparison{--route-step-height:176px}}
.screenshot-link{display:block;cursor:zoom-in}.screenshot-link:focus-visible{outline:3px solid #253d98;outline-offset:-3px}.guide-intro .guide-image-note{margin:12px 0 0;font-size:12px;line-height:1.5;letter-spacing:normal;text-transform:none;font-weight:400;color:#536075}.notification-stack .screen:nth-child(2){max-width:640px}.help-example{max-width:560px}.document-grid img{height:auto;object-fit:contain}
</style>
